version: '3'

services:
  ehrbase:
    image: ehrbase/ehrbase:next
    ports:
      - 8080:8080
    networks:
      - ehrbase-net
    env_file:
      - .env.ehrbase
    environment:
      DB_URL: jdbc:postgresql://ehrbase-open-postgres-sandbox.postgres.database.azure.com:5432/postgres
      DB_USER_ADMIN: postgres
      DB_PASS_ADMIN: UKWT0Q0W2QL1G3X5$
      DB_USER: postgres
      DB_PASS: UKWT0Q0W2QL1G3X5$
    restart: on-failure



networks:
  ehrbase-net: {}
