spring:
  datasource:
    url: jdbc:postgresql://c-cosmosdb.ofqt4ngm4dbcuv.postgres.cosmos.azure.com:5432/citus
    username: citus
    password: GFG7Q4204P0HM35A$
    hikari:
      maximum-pool-size: 50
      max-lifetime: 1800000
      minimum-idle: 10
  flyway:
    schemas: ehr
    user: citus
    password: GFG7Q4204P0HM35A$

security:
  authType: NONE


server:
  port: 8080
  # Optional custom server nodename
  # nodename: 'local.test.org'

  aqlConfig:
    # if true, WHERE clause is using jsquery, false uses SQL only
    useJsQuery: false
    # ignore unbounded item in path starting with one of
    ignoreIterativeNodeList: 'events,activities,content'
    # how many embedded jsonb_array_elements(..) are acceptable? Recommended == 1
    iterationScanDepth: 1

  servlet:
    context-path: /ehrbase
