#spring:
#  rabbitmq:
#    virtual-host: authorization




#hip.pdp.rabbitmq.virtual-host:/
hip.pdp.rabbitmq.host: localhost
hip.pdp.rabbitmq.username: guest
hip.pdp.rabbitmq.password: guest






    
    
    
    

policyChangeQueueName: policy.changes

xacml.persistence:
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.hbm2ddl.auto: update
  hibernate.default_schema: ehr
  javax.persistence.jdbc.driver: org.postgresql.Driver
  javax.persistence.jdbc.url: jdbc:postgresql://localhost:5432/ehrbase
  javax.persistence.jdbc.user: ehrbase_restricted
  javax.persistence.jdbc.password: ehrbase_restricted
