name: Build and deploy Docker image for YugabyteDB

on:
  push:
    branches: [ feature/yuga_trial ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn -B package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ehrbase/ehrbase:yugabyte-experimental

