name: Build and deploy Docker image for YugabyteDB

on:
  push:
    branches: [ feature/yuga_trial ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (linux/amd64)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ehrbase/ehrbase:yugabyte-experimental-amd64

      - name: Build and push (linux/arm64)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ehrbase/ehrbase:yugabyte-experimental-arm64

      - name: Create and push MultiArch Manifest
        run: |
          docker buildx imagetools create \
              ehrbase/ehrbase:yugabyte-experimental-amd64 \
              ehrbase/ehrbase:yugabyte-experimental-arm64 \
              -t ehrbase/ehrbase:yugabyte-experimental
          docker pull ehrbase/ehrbase:yugabyte-experimental

      - name: Inspect MultiArch Manifest
        run: docker manifest inspect ehrbase/ehrbase:yugabyte-experimental